name: hello-world

on: push

jobs:
  hello-world-job:

    runs:on: ubuntu-latest

    steps:
      - name: check out respository code
        uses: actions/checkouy@v4
      - run: echo "$(cat hello_world.txt)"
